"use client";
import { useState } from "react";
import Link from "next/link";
import { Check, LockKeyhole, ShoppingBag } from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";

const items = [
 ["Avatar", "Nuevos personajes para el perfil", 120], ["Avatar Outfit", "Ropa para el avatar", 90], ["Avatar Accessories", "Lentes, gorros y audífonos", 75], ["Profile Frame", "Marcos alrededor del avatar", 100], ["Animated Frame", "Marcos con animaciones sutiles", 240], ["Profile Background", "Fondos para el perfil", 140], ["Dashboard Theme", "Cambia la estética del dashboard", 300], ["Learning Path Theme", "Personaliza el mapa de aprendizaje", 280], ["Lesson Theme", "Apariencia alternativa de las lecciones", 220], ["Profile Title", "Títulos para mostrar en tu perfil", 110], ["Rare Profile Title", "Títulos exclusivos", 450], ["Streak Flame", "Cambia el aspecto de tu racha", 180], ["XP Animation", "Nuevos efectos al ganar XP", 160], ["Lesson Complete Effect", "Celebración al terminar una lección", 190], ["Checkpoint Effect", "Celebración de punto de control", 210], ["Achievement Showcase Slot", "Muestra un logro favorito adicional", 350], ["Profile Badge", "Insignias decorativas", 100], ["Speech Bubble Style", "Personaliza mensajes y tutoriales", 130], ["Seasonal Cosmetics", "Colección cosmética de temporada", 260], ["Mystery Box", "Un cosmético nuevo al azar", 200],
] as const;
export default function ShopPage(){const [balance,setBalance]=useState(460);const [owned,setOwned]=useState<string[]>([]);return <main className="min-h-screen bg-muted/30"><div className="mx-auto max-w-6xl px-5 py-8"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-primary">Personaliza tu experiencia</p><h1 className="mt-2 text-3xl font-black">Tienda de Bytes</h1><p className="mt-2 text-sm text-muted-foreground">Los Bytes solo desbloquean elementos cosméticos. Tu progreso de aprendizaje nunca depende de una compra.</p></div><div className="flex gap-3"><span className="rounded-xl border bg-card px-4 py-2 font-black">{balance} Bytes</span><Link href="/student/dashboard" className={buttonVariants({variant:"outline"})}>Volver</Link></div></header><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(([name,description,price],index)=>{const bought=owned.includes(name);const affordable=balance>=price;return <article key={name} className="flex flex-col rounded-2xl border bg-card p-5"><span className={`mb-4 grid size-12 place-items-center rounded-xl ${index%2 ? "bg-chart-2/10 text-chart-2":"bg-primary/10 text-primary"}`}><ShoppingBag/></span><h2 className="font-black">{name}</h2><p className="mt-1 flex-1 text-sm text-muted-foreground">{description}</p><Button className="mt-5 w-full" variant={bought?"secondary":affordable?"default":"outline"} disabled={bought||!affordable} onClick={()=>{setBalance(v=>v-price);setOwned(v=>[...v,name])}}>{bought?<><Check/>Adquirido</>:affordable?`${price} Bytes`:<><LockKeyhole/>Faltan {price-balance} Bytes</>}</Button></article>})}</div></div></main>}