export type Achievement = { title: string; description: string; category: string; target: number; progress: number; secret?: boolean };

const definitions: Array<[string, string, string, number]> = [
  ["First Byte", "Completa tu primera lección", "Lecciones", 1], ["Byte by Byte", "Completa 5 lecciones", "Lecciones", 5], ["Ten Down!", "Completa 10 lecciones", "Lecciones", 10], ["Getting Serious", "Completa 25 lecciones", "Lecciones", 25], ["Half a Hundred", "Completa 50 lecciones", "Lecciones", 50], ["Triple Digits", "Completa 100 lecciones", "Lecciones", 100], ["Unstoppable", "Completa 150 lecciones", "Lecciones", 150], ["Level Conqueror", "Completa 200 lecciones", "Lecciones", 200],
  ["Checkpoint!", "Llega a tu primer checkpoint", "Camino", 1], ["Pathfinder", "Completa 5 checkpoints", "Camino", 5], ["Section Master", "Completa una sección de 40 lecciones", "Camino", 1], ["Bright Scholar", "Completa 3 secciones", "Camino", 3], ["The Final Byte", "Completa las 5 secciones de un nivel", "Camino", 5],
  ["Fresh Start", "Estudia 2 días consecutivos", "Rachas", 2], ["On Fire", "Mantén un streak de 3 días", "Rachas", 3], ["One Week Strong", "Mantén un streak de 7 días", "Rachas", 7], ["Two Weeks Stronger", "Mantén un streak de 14 días", "Rachas", 14], ["Monthly Legend", "Mantén un streak de 30 días", "Rachas", 30], ["Unbreakable", "Mantén un streak de 60 días", "Rachas", 60], ["Centurion", "Mantén un streak de 100 días", "Rachas", 100],
  ["Weekend Warrior", "Estudia sábado y domingo", "Hábitos", 2], ["Monday Hero", "Completa una lección un lunes", "Hábitos", 1], ["Early Bird", "Completa una lección antes de las 8 AM", "Hábitos", 1], ["Night Owl", "Completa una lección después de las 10 PM", "Hábitos", 1],
  ["Perfect Byte", "Obtén 100% en una lección", "Precisión", 1], ["Perfectionist", "Obtén 100% en 5 lecciones", "Precisión", 5], ["Flawless Ten", "Obtén 100% en 10 lecciones", "Precisión", 10],
  ["Grammar Rookie", "Completa 10 ejercicios de gramática", "Práctica", 10], ["Grammar Nerd", "Completa 50 ejercicios de gramática", "Práctica", 50], ["Grammar Wizard", "Completa 100 ejercicios de gramática", "Práctica", 100], ["Word Collector", "Aprende 25 palabras", "Vocabulario", 25], ["Vocabulary Hunter", "Aprende 100 palabras", "Vocabulario", 100], ["Walking Dictionary", "Aprende 500 palabras", "Vocabulario", 500],
  ["Bookworm", "Completa 25 readings", "Habilidades", 25], ["Story Hunter", "Completa 100 readings", "Habilidades", 100], ["Finding My Voice", "Completa tu primer speaking", "Habilidades", 1], ["Chatterbox", "Completa 25 speaking practices", "Habilidades", 25], ["Speak Up!", "Completa 100 speaking practices", "Habilidades", 100], ["Dear Diary...", "Completa tu primer writing", "Habilidades", 1], ["Little Writer", "Completa 25 writing practices", "Habilidades", 25], ["English Author", "Completa 100 writing practices", "Habilidades", 100],
  ["Quest Accepted", "Completa tu primera daily quest", "Quests", 1], ["Adventurer", "Completa 25 daily quests", "Quests", 25], ["Quest Master", "Completa 100 daily quests", "Quests", 100], ["Weekly Champion", "Completa todas tus quests semanales", "Quests", 1], ["Comeback Kid", "Completa una lección después de 7 días", "Especiales", 1], ["Second Chance", "Corrige un ejercicio que respondiste mal", "Especiales", 1], ["Never Give Up", "Corrige 50 errores", "Especiales", 50], ["Byte Millionaire", "Acumula 1.000 Bytes en total", "Especiales", 1000],
];

export const achievements: Achievement[] = definitions.map(([title, description, category, target], index) => ({ title, description, category, target, progress: index < 3 ? target : index % 4 === 0 ? Math.min(target - 1, Math.ceil(target * .35)) : 0 }));
achievements.push({ title: "???", description: "Achievement secreto por descubrir", category: "Secretos", target: 1, progress: 0, secret: true });