export const DAILY_QUOTES = [
  ["English opens doors.", "El inglés abre puertas."],
  ["Your voice deserves to travel.", "Tu voz merece viajar."],
  ["One word today, a world tomorrow.", "Una palabra hoy, un mundo mañana."],
  ["Speak bravely, grow freely.", "Habla con valentía, crece con libertad."],
  ["Every lesson moves you forward.", "Cada lección te hace avanzar."],
  ["Fluency begins with trying.", "La fluidez comienza intentándolo."],
  ["Small steps cross big borders.", "Los pequeños pasos cruzan grandes fronteras."],
  ["Learn today, connect tomorrow.", "Aprende hoy, conecta mañana."],
  ["Your future speaks English.", "Tu futuro habla inglés."],
  ["Mistakes mean you are learning.", "Los errores significan que estás aprendiendo."],
  ["Practice turns courage into confidence.", "La práctica convierte el valor en confianza."],
  ["New words create new possibilities.", "Nuevas palabras crean nuevas posibilidades."],
  ["You are closer than yesterday.", "Estás más cerca que ayer."],
  ["Say it, learn it, own it.", "Dilo, apréndelo, hazlo tuyo."],
  ["Consistency makes language feel natural.", "La constancia hace que el idioma se sienta natural."],
  ["A new language is a new lens.", "Un nuevo idioma es una nueva perspectiva."],
  ["Your next opportunity starts here.", "Tu próxima oportunidad empieza aquí."],
  ["Keep going—your world is expanding.", "Sigue adelante: tu mundo se está ampliando."],
  ["English connects ideas and people.", "El inglés conecta ideas y personas."],
  ["Confidence grows one sentence at a time.", "La confianza crece una frase a la vez."],
  ["Today’s practice is tomorrow’s freedom.", "La práctica de hoy es la libertad de mañana."],
  ["Be curious in every language.", "Sé curioso en todos los idiomas."],
  ["Listen closely. Speak boldly.", "Escucha con atención. Habla con decisión."],
  ["Your accent tells your story.", "Tu acento cuenta tu historia."],
  ["Progress sounds like practice.", "El progreso suena a práctica."],
  ["Learn English, meet the world.", "Aprende inglés, conoce el mundo."],
  ["Every conversation is a chance.", "Cada conversación es una oportunidad."],
  ["You can say more every day.", "Cada día puedes decir más."],
  ["Dream globally, start locally.", "Sueña globalmente, empieza localmente."],
  ["Your effort is building fluency.", "Tu esfuerzo está construyendo fluidez."],
  ["A few minutes can change your path.", "Unos minutos pueden cambiar tu camino."],
  ["Words help your ideas travel.", "Las palabras ayudan a que tus ideas viajen."],
  ["Learn the language of opportunity.", "Aprende el idioma de las oportunidades."],
  ["Each phrase is a tiny victory.", "Cada frase es una pequeña victoria."],
  ["Show up, even for five minutes.", "Hazte presente, aunque sean cinco minutos."],
  ["Understanding begins with one question.", "Comprender comienza con una pregunta."],
  ["Your goals are worth the practice.", "Tus metas merecen la práctica."],
  ["Turn hesitation into conversation.", "Convierte la duda en conversación."],
  ["The world has more to tell you.", "El mundo tiene más que contarte."],
  ["English brings your talent further.", "El inglés lleva tu talento más lejos."],
  ["Practice makes possibilities real.", "La práctica hace reales las posibilidades."],
  ["Keep learning. Keep becoming.", "Sigue aprendiendo. Sigue creciendo."],
  ["Your next connection is one hello away.", "Tu próxima conexión está a un hola de distancia."],
  ["Read widely, speak freely.", "Lee ampliamente, habla libremente."],
  ["Today is a good day to try.", "Hoy es un buen día para intentarlo."],
  ["Build a habit, discover a world.", "Crea un hábito, descubre un mundo."],
  ["Let your ideas be understood.", "Haz que tus ideas sean comprendidas."],
  ["Every review makes recall stronger.", "Cada repaso fortalece tu memoria."],
  ["Your English journey is uniquely yours.", "Tu camino con el inglés es solo tuyo."],
  ["Start small. Speak big.", "Empieza poco a poco. Habla en grande."],
] as const;